import os
import time
from pathlib import Path

from dotenv import load_dotenv
from google import genai


# ---------------------------------------------------------
# Load .env
# ---------------------------------------------------------

ROOT_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = ROOT_DIR / ".env"

load_dotenv(ENV_FILE)


# ---------------------------------------------------------
# Configuration
# ---------------------------------------------------------

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "").strip()

GEMINI_MODEL = os.getenv(
    "GEMINI_MODEL",
    "gemini-3.8-flash"
).strip()

DEMO_MODE = os.getenv(
    "DEMO_MODE",
    "false"
).strip().lower() == "true"


# ---------------------------------------------------------
# Validation
# ---------------------------------------------------------

if not GEMINI_API_KEY and not DEMO_MODE:
    raise RuntimeError(
        "GEMINI_API_KEY is missing. "
        "Please add your Gemini API key to the .env file."
    )


# ---------------------------------------------------------
# Gemini client
# ---------------------------------------------------------

client = None

if GEMINI_API_KEY:
    try:
        client = genai.Client(
            api_key=GEMINI_API_KEY
        )
    except Exception as exc:
        if not DEMO_MODE:
            raise RuntimeError(
                f"Could not initialize Gemini client: {exc}"
            )


# ---------------------------------------------------------
# Demo document
# ---------------------------------------------------------

def create_demo_document(
    document_type: str,
    parties: str,
    terms: str,
    effective_date: str,
    jurisdiction: str,
    additional_instructions: str,
) -> str:

    return f"""
{document_type.upper()}

Effective Date: {effective_date}

JURISDICTION
{jurisdiction}

PARTIES
{parties}

TERMS
{terms}

ADDITIONAL INSTRUCTIONS
{additional_instructions}

------------------------------------------------------------

DEMO DOCUMENT

This is a demonstration document generated by LegalEase.

The document contains the information supplied by the user.
For an actual legal document, the generated content should be
reviewed by a qualified legal professional before use.

------------------------------------------------------------

SIGNATURES

Party 1: ______________________________

Name: _________________________________

Date: __________________________________


Party 2: ______________________________

Name: _________________________________

Date: __________________________________
""".strip()


# ---------------------------------------------------------
# Prompt builder
# ---------------------------------------------------------

def build_legal_prompt(
    document_type: str,
    parties: str,
    terms: str,
    effective_date: str,
    jurisdiction: str,
    additional_instructions: str,
) -> str:

    prompt = f"""
You are the AI drafting engine for an application called LegalEase.

Your task is to create a clear, professional LEGAL DOCUMENT DRAFT
based only on the information supplied by the user.

IMPORTANT:
- This is a draft for informational and editing purposes.
- Do not claim that the document is legally valid or guaranteed.
- Do not invent important facts that the user did not provide.
- If information is missing, use a neutral placeholder such as
  [INSERT INFORMATION].
- Use professional legal drafting language.
- Organize the document using clear headings and numbered clauses.
- Include signature sections when appropriate.
- Make the document easy to copy into DOCX and PDF.
- Do not use Markdown code fences.
- Do not add unnecessary explanations before or after the document.

DOCUMENT TYPE:
{document_type}

PARTIES:
{parties}

EFFECTIVE DATE:
{effective_date}

JURISDICTION:
{jurisdiction}

IMPORTANT TERMS:
{terms}

ADDITIONAL USER INSTRUCTIONS:
{additional_instructions}

Create the complete legal document draft now.

Suggested general structure where appropriate:

1. TITLE
2. DATE
3. PARTIES
4. PURPOSE / RECITALS
5. DEFINITIONS
6. TERMS AND CONDITIONS
7. OBLIGATIONS
8. PAYMENT / COMPENSATION, if applicable
9. CONFIDENTIALITY, if applicable
10. TERMINATION, if applicable
11. DISPUTE RESOLUTION
12. GOVERNING LAW
13. GENERAL PROVISIONS
14. SIGNATURES

Only include sections relevant to the selected document type.
""".strip()

    return prompt


# ---------------------------------------------------------
# Error classification
# ---------------------------------------------------------

def is_retryable_error(error_text: str) -> bool:

    retry_words = [
        "429",
        "500",
        "502",
        "503",
        "504",
        "UNAVAILABLE",
        "RESOURCE_EXHAUSTED",
        "DEADLINE_EXCEEDED",
        "temporarily unavailable",
        "high demand",
        "overloaded",
    ]

    error_lower = error_text.lower()

    return any(
        word.lower() in error_lower
        for word in retry_words
    )


# ---------------------------------------------------------
# Gemini generation
# ---------------------------------------------------------

def call_gemini(prompt: str) -> str:

    if client is None:
        raise RuntimeError(
            "Gemini client is not initialized."
        )

    max_attempts = 4

    delays = [
        2,
        4,
        8,
        12,
    ]

    last_error = None

    for attempt in range(max_attempts):

        try:

            print(
                f"[LegalEase] Gemini request "
                f"attempt {attempt + 1}/{max_attempts}"
            )

            # Current Gemini Interactions API
            interaction = client.interactions.create(
                model=GEMINI_MODEL,
                input=prompt,
            )

            # Preferred output property
            generated_text = getattr(
                interaction,
                "output_text",
                None
            )

            if generated_text:
                generated_text = generated_text.strip()

            # Safety fallback in case output_text isn't populated
            if not generated_text:

                steps = getattr(
                    interaction,
                    "steps",
                    []
                )

                text_parts = []

                for step in steps:

                    content = getattr(
                        step,
                        "content",
                        []
                    )

                    for block in content:

                        block_text = getattr(
                            block,
                            "text",
                            None
                        )

                        if block_text:
                            text_parts.append(
                                block_text
                            )

                generated_text = "\n".join(
                    text_parts
                ).strip()

            if not generated_text:

                raise RuntimeError(
                    "Gemini returned an empty response."
                )

            print(
                "[LegalEase] Gemini generation successful."
            )

            return generated_text

        except Exception as exc:

            last_error = exc

            error_text = str(exc)

            print(
                f"[LegalEase] Gemini error: {error_text}"
            )

            # Don't retry invalid model / authentication errors
            if "404" in error_text:
                raise RuntimeError(
                    f"Gemini model '{GEMINI_MODEL}' "
                    f"was not found or is not available "
                    f"for this API key.\n\n"
                    f"Current configured model: "
                    f"{GEMINI_MODEL}\n\n"
                    f"Original error:\n{error_text}"
                )

            if "401" in error_text or "403" in error_text:
                raise RuntimeError(
                    "Gemini API authentication failed.\n\n"
                    "Check that your GEMINI_API_KEY in .env "
                    "is correct and active."
                )

            # Retry temporary server/capacity errors
            if is_retryable_error(error_text):

                if attempt < max_attempts - 1:

                    delay = delays[attempt]

                    print(
                        f"[LegalEase] Temporary Gemini "
                        f"error. Retrying in {delay} seconds..."
                    )

                    time.sleep(delay)

                    continue

            # Non-retryable error
            raise RuntimeError(
                f"Gemini API request failed:\n{error_text}"
            )

    raise RuntimeError(
        f"Gemini API request failed after "
        f"{max_attempts} attempts:\n{last_error}"
    )


# ---------------------------------------------------------
# Public function used by FastAPI
# ---------------------------------------------------------

def generate_legal_document(
    document_type: str,
    parties: str,
    terms: str,
    effective_date: str,
    jurisdiction: str = "India",
    additional_instructions: str = "",
) -> str:

    # Demo mode
    if DEMO_MODE:

        print(
            "[LegalEase] DEMO_MODE=true. "
            "Using local demo generator."
        )

        return create_demo_document(
            document_type=document_type,
            parties=parties,
            terms=terms,
            effective_date=effective_date,
            jurisdiction=jurisdiction,
            additional_instructions=additional_instructions,
        )

    # Build AI prompt
    prompt = build_legal_prompt(
        document_type=document_type,
        parties=parties,
        terms=terms,
        effective_date=effective_date,
        jurisdiction=jurisdiction,
        additional_instructions=additional_instructions,
    )

    # Call Gemini
    return call_gemini(prompt)